### ISSUE TITLE
broken system font (white/full-width numbers)

### ISSUE THREAD

**Issue by KiaraGrouwstra** [KiaraGrouwstra/nix-config#103]
splitting from #52 to tackle #29 for Gnome while leaving KDE unaffected.

> related to Noto font. I actually already had it as preferred rather than as a hard overwrite, so commenting now. I didn't set noto/blob fonts as system font either. :/

**Comment by tycho01** [comment]
uh, font stuff seems separate from desktop manager, so how do I handle this separately for them?

**Comment by KiaraGrouwstra** [comment]
new repo works
