### ISSUE TITLE
home-manager

### ISSUE THREAD

**Issue by KiaraGrouwstra** [KiaraGrouwstra/nix-config#109]
[`home-manager`](https://github.com/rycee/home-manager) [manages] a user environment using Nix.

**Comment by tycho01** [comment]
more intro [here](https://nixos.wiki/wiki/Home_Manager). this thing can probably replace the hacky stuff I did in my repo for this.

**Comment by tycho01** [comment]
wait, it seems `home-manager`:
- functions as a NixOS knock-off to handle system config for Nix users on other operating systems;
- lets you sorta symlink dotfiles or something, which is what I kinda did with my hacky scripts here too, except I actually had a mechanism to upstream changes. I should probably check if they offer that as well.

**Comment by tycho01** [comment]
actually the former point is potentially relevant for me now on Arch.

**Comment by KiaraGrouwstra** [comment]
fixed in https://codeberg.org/kiara/cfg
